fix indentation
Signed-off-by: Abhishek Rai <rai.abhishek90@gmail.com>

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -9,11 +9,11 @@ sed --version 2>/dev/null
 
 # Update chart version
 if [ $? -eq 0 ]; then
-	sed -i "s/version: .*/version: $VERSION/" helm/promgithub/Chart.yaml
-	sed -i "s/appVersion: .*/appVersion: \"$VERSION\"/" helm/promgithub/Chart.yaml
+    sed -i "s/version: .*/version: $VERSION/" helm/promgithub/Chart.yaml
+    sed -i "s/appVersion: .*/appVersion: \"$VERSION\"/" helm/promgithub/Chart.yaml
 else
-	sed -i '' "s/version: .*/version: $VERSION/" helm/promgithub/Chart.yaml
-	sed -i '' "s/appVersion: .*/appVersion: \"$VERSION\"/" helm/promgithub/Chart.yaml
+    sed -i '' "s/version: .*/version: $VERSION/" helm/promgithub/Chart.yaml
+    sed -i '' "s/appVersion: .*/appVersion: \"$VERSION\"/" helm/promgithub/Chart.yaml
 fi
 
 # Check if the Chart.yaml was updated, stage the change
@@ -21,8 +21,8 @@ git add helm/promgithub/Chart.yaml
 
 # Exit with non-zero status if the make command fails
 if [ $? -ne 0 ]; then
- echo "Pre-commit hook failed (make target did not complete)"
- exit 1
+    echo "Pre-commit hook failed (make target did not complete)"
+    exit 1
 fi
 
 echo "Pre-commit hook completed successfully"
